# SonarQube server configuration
sonarqube:
  url: "https://sonarqube.cosmotech.com/"

# Repositories to scan
repositories:
# Test repositories
  - name: "python-pad-project"
    url: "https://github.com/Cosmo-Tech/python-bad-project.git"
    branches: ["main"]
    project_key: "python-bad-project"
    
  - name: "cosmotech-api"
    url: "https://github.com/Cosmo-Tech/cosmotech-api.git"
    branches: ["main", "release/v3.3"]
    project_key: "cosmotech-api"

# web app 
# API
# python
# SDK
