# SonarQube server configuration
sonarqube:
  url: "http://localhost:9000"

# Repositories to scan
repositories:
# Self-check repositories
  - name: "python-bad-project"
    url: "https://github.com/Cosmo-Tech/python-bad-project.git"
    branches: ["main"]

  - name: "sonarqube-scanner"
    url: "https://github.com/Cosmo-Tech/sonarqube-scanner.git"
    branches: ["main"]

  - name: "sonarqube-reporter"
    url: "https://github.com/Cosmo-Tech/sonarqube-reporter.git"
    branches: ["main"]

# platform
  - name: "example-project-name"
    url: "https://github.com/Cosmo-Tech/example.git"
    branches: ["main", "release/v5", "release/v6"]

  - name: "other-project"
    url: "https://bitbucket.corporate.com/cother-project.git"
    branches: ["main", "release/v8", "release/v4"]