name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install project
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install '.[test]'

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/ --cov